# Numpy

In [1]:
!pip install numpy

In [3]:
import numpy as np

In [21]:
#1d array
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)
arr_1d.shape

[1 2 3 4 5]


(5,)

In [43]:
#two dimensional arrays 
arr_2d=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr_2d) 
arr_2d.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [11]:
#with default values
default_arr=np.zeros(3)
print(default_arr)

[0. 0. 0.]


In [13]:
default_arr_ones=np.ones((2,3))
print(default_arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
filled_arr=np.full((2,2),5)
print(filled_arr)

[[5 5]
 [5 5]]


In [25]:
#creating sequences of numbers in numpy
#arange (start,stop,step)
seq_arr=np.arange(1,10,2)
print(seq_arr)

[1 3 5 7 9]


In [39]:
#creating identity matrices
identity_matrix=np.eye(3)
print(identity_matrix)
print(identity_matrix.size)    # total number of elements in arr
print(identity_matrix.ndim)    # number of dimensions

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
9
2


In [41]:
arr_one=np.array([1,2,3])
arr_two=np.array([[1,2,3],[4,5,6]])
arr_three=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(arr_one)
print(arr_one.ndim)
print(arr_two)
print(arr_two.ndim)
print(arr_three)
print(arr_three.ndim)

[1 2 3]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
3


In [45]:
#dtype= data type of array
arr=np.array([11,23,33.4])
print(arr.dtype)

float64


In [53]:
#astype
arr=np.array([11,22.4,34.4])
print(arr.dtype)
int_arr=arr.astype(int)
print(int_arr)


float64
[11 22 34]


In [15]:
#numpy vectorized operation
arr=np.array([1,2,3,4,5])
print(arr*2)
print(arr**2)
arr2=np.array([6,7,8,9,10])
print(arr+arr2)

[ 2  4  6  8 10]
[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [21]:
#statastical concepts
data=np.array([11,12,23,44,55])
sum=np.sum(data)   #sum
print("Sum:",sum)
min=np.min(data)  #min
print("Min:",min)
max=np.max(data)  #max
print("max:",max)
mean=np.mean(data)  # mean
print("Mean:",mean)
median=np.median(data)  #median
print("Median:",median)
std_d=np.std(data)  #standard deviation
print("Standard deviation:",std_d)
var=np.var(data)   #variance
print("variance:",var)

Sum: 145
Min: 11
max: 55
Mean: 29.0
Median: 23.0
Standard deviation: 17.60681686165901
variance: 310.0


In [24]:
#universal function
arr=np.array([1,2,3,4,5])
sqrt=np.sqrt(arr)   #square root
print("sqrt:",sqrt)
exp=np.exp(arr)   #exponential
print("exp:",exp)
log=np.log(arr)  #log
print("log:",log)

sqrt: [1.         1.41421356 1.73205081 2.         2.23606798]
exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [38]:
#indexing & slicing
""" 
Indexing:
array[index]  :1D array
array[row,column]  :2D array
"""
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[2])
"""
Slicing:
array[start,stop,step]
"""
arr1=np.array([1,2,3,4,5,6])
print(arr1[1:4])
print(arr1[:4])
print(arr1[::2])
print(arr1[::-1])

1
3
[2 3 4]
[1 2 3 4]
[1 3 5]
[6 5 4 3 2 1]


In [40]:
#fancy indexing: selecting multiple elements at ones
arr=np.array([1,2,3,4,5,6])
print(arr[[0,1,2]])

[1 2 3]


In [42]:
#boolean masking
arr2=np.array([10,20,30,40,50])
print(arr2[arr2>25])

[30 40 50]


In [50]:
#reshaping
arr=np.array([1,2,3,4])
reshaped=arr.reshape(2,2)
print(reshaped)

[[1 2]
 [3 4]]


In [54]:
#flattening
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d.ravel())   #returns view of array
print(arr2d.flatten())  #return copy of array

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [56]:
#inserting
"""
np.insert(array,index,value,axis)
"""
arr=np.array([1,2,3,4,5])
new=np.insert(arr,2,100)
print(arr)
print(new)


[1 2 3 4 5]
[  1   2 100   3   4   5]


In [64]:
arr_2d=np.array([[1,2,3],[4,5,6]])
#insert a new row at index 1
new=np.insert(arr_2d,1,[7,8,9],axis=0)
print(new)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [70]:
#append
arr=np.array([1,2,3,4,5])
print(np.append(arr,[6,7,8,9]))

[1 2 3 4 5 6 7 8 9]


In [76]:
#concatenate
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
new=np.concatenate((arr1,arr2))
print(new)

[1 2 3 4 5 6 7 8]


In [84]:
#delete
arr=np.array([10,20,30,40])
new=np.delete(arr,[0])
print(new)
arr_2d=np.array([[1,2,3],[4,5,6]])
new_2d=np.delete(arr_2d,0,axis=0)
print(new_2d)

[20 30 40]
[[4 5 6]]


In [86]:
#stacking
"""
vertically
horizontally
vstack()  row wise
hstack()  column wise
"""
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.vstack((arr1,arr2)))   #vertical stack
print(np.hstack((arr1,arr2)))   #horizontal stack

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [94]:
#splitting
"""
np.split()
np.hsplit()
np.vsplit()
"""
arr=np.array([1,2,3,4])
print(np.split(arr,2))

[array([1, 2]), array([3, 4])]


In [96]:
#Handeling missing values
arr=np.array([1,2,np.nan,4,np.nan])   # nan= not a number
print(np.isnan(arr))

[False False  True False  True]


In [104]:
#infinite 
arr=np.array([1,2,np.inf,4,np.inf])   # inf=infinite values
print(np.isinf(arr))
print(arr)
cleaned_arr=np.nan_to_num(arr,posinf=1000,neginf=-1000)  #nan_to_num= replacing infinite values
print(cleaned_arr)

[False False  True False  True]
[ 1.  2. inf  4. inf]
[   1.    2. 1000.    4. 1000.]


In [108]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [116]:
#random numbers
print(np.random.rand(5))   # float  5 random numbers between 0 and 1
print(np.random.rand(2,3))  #float

[0.03533221 0.22781425 0.00404789 0.33234729 0.02861974]
[[0.74376699 0.87099861 0.75264015]
 [0.61508581 0.28212772 0.14836438]]


In [122]:
#random numbers- normal distribution
print(np.random.randn(5))   # 5 random numbers 'mean:0,std dev:1'
print(np.random.randn(2,3))  

[-1.22499659 -0.6450488   0.94724052 -0.46880717  0.36016592]
[[-1.63295881 -0.58874715  1.0326009 ]
 [-0.21437101  0.44827094  1.36868735]]


In [128]:
#random integres
print(np.random.randint(1,10)) 
print(np.random.randint(1,10,size=5))   

7
[4 1 7 8 2]


In [132]:
#random choice from array
arr=np.array([1,2,3,4,5])
print(np.random.choice(arr,size=3))

[4 5 3]


In [146]:
#random seed- to get same result every time
np.random.seed(42)    #always start the random numbers from the same place
print(np.random.rand(3))
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]
